
name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4
    - run: docker build . -t deepak003007/next-js-app
    - run: echo "${{secrets.DOCKER_HUB_PASSWORD}}" | docker login -u deepak003007 --password-stdin 
    - run: docker push deepak003007/next-js-app:latest